(setq a 10)
(setq b 3)
(setq c (+ a b))
(setq d (- a b))
(setq e (* a b))
(setq f (/ a b))
(setq g (mod a b))
(setq eq_r (= c 13))
(setq neq_r (/= a b))
(setq lt_r (< b a))
(setq gt_r (> a b))
(setq lte_r (<= b a))
(setq gte_r (>= a b))
(setq and_r (and (> a 5) (< b 10)))
(setq or_r (or (= a 0) (> b 0)))
(setq not_r (not (= a 0)))
(princ c)
(princ d)
(princ e)
(princ neq_r)
(princ and_r)
