(setq primo 0)
(setq n 0)
(setq m 0)

(defun main ()
(setq main_d 0)
(setq main_i 0)
(setq main_p 0)
(setf main_i 1)
(setf n 1)
(setf m 100)
(setf main_i 1)
(loop while (<= main_i m) do
(setf main_d 2)
(setf primo 1)
(loop while (and (= primo 1) (< main_d main_i)) do
(setf main_p (mod main_i main_d))
(if (= main_p 0)
(setf primo 0))
(setf main_d (+ main_d 1)))
(if (= primo 1)
(progn
(princ main_i)
(princ " ")))

(setf main_i (+ main_i 1)))
)
 (main)
